server:
  port: 8888

spring:
  application:
    name: service-config-ser
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mstao/spring-cloud-config
          searchPaths: /**
          label: master
          username:
          password:
  rabbitmq: #RabbitMQ相关的配置
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
      ipAddress: 127.0.0.1

management:
  security:
    enabled: false #是否开启actuator安全认证